In [1]:
import numpy as np

In [3]:
temp_1d = np.array([1,2,3]) # 1D array

In [4]:
temp_1d.shape

(3,)

In [5]:
temp_1d.size

3

In [6]:
temp_2d = np.array([[1,2],[3,4]]) # 2D Array

In [7]:
temp_2d.shape

(2, 2)

In [9]:
temp_2d.size

4

In [10]:
temp_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [11]:
temp_3d.shape

(2, 2, 2)

In [12]:
temp_3d.size

8

In [13]:
temp_1d

array([1, 2, 3])

In [14]:
temp_2d

array([[1, 2],
       [3, 4]])

In [15]:
temp_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
np.zeros(5) # generates 1d array

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,2)) # generate 2d array of 3 rows and 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.zeros((1,4,3)) # generates 3d array, we get one 2 row and 3 column matrix

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
np.zeros((2,4,3)) # generates 3d array, we get two 4 rows and 3 column matrix

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
temp_1d

array([1, 2, 3])

In [29]:
temp_1d[0]

1

In [31]:
temp_1d[1:-1]

array([2])

In [32]:
temp_2d

array([[1, 2],
       [3, 4]])

In [33]:
temp_2d[0] # returns full first row

array([1, 2])

In [34]:
temp_2d[1] # returns full second row

array([3, 4])

In [35]:
temp_2d[0][0]

1

In [37]:
temp_2d[0][1] 

2

In [38]:
temp_2d[0,1]

2

In [39]:
temp_2d[-1,-1]

4

In [40]:
temp_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [41]:
temp_3d[1,0,0]

5

In [42]:
temp_3d[0,-1,-1]

4

In [45]:
start,stop,step = 1,10,2
np.arange(start,stop,step)

array([1, 3, 5, 7, 9])

In [50]:
two_d = np.array([np.arange(1,6),np.arange(6,11),np.arange(1,11,2),
                 np.arange(1,14,3),np.arange(1,22,5)])

In [51]:
two_d # this is a 5 x 5 matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  3,  5,  7,  9],
       [ 1,  4,  7, 10, 13],
       [ 1,  6, 11, 16, 21]])

In [52]:
two_d[:2] # to get first 2 rows

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
two_d[:2,:2] # to get only first 2 columns from first 2 rows

array([[1, 2],
       [6, 7]])

In [ ]:
# syntax of slicing in 2d array is [start_row_index:end_row_index:steps, start_col_index::]
# for 1d -> [::]
# for 2d -> [::,::]
# for 3d -> [::,::,::]

In [54]:
temp_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [57]:
temp_3d[1:,:1,:1]

array([[[5]]])

In [58]:
temp_3d[:,:1,:1]

array([[[1]],

       [[5]]])

In [ ]:
# reshape array

In [59]:
temp_1d

array([1, 2, 3])

In [61]:
temp_1d.reshape(3,1) # 1d to 2d (3 rows 1 column)

array([[1],
       [2],
       [3]])

In [62]:
temp_2d

array([[1, 2],
       [3, 4]])

In [65]:
temp_2d.reshape(1,4) # 2 row 2 column ---> 1 row 4 columns

array([[1, 2, 3, 4]])

In [68]:
temp_3d.flatten() # 3d to 1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
temp_3d.reshape(2,4) # 3d to 2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])