In [29]:
#solution
def find_length(inp):
    length = 0
    while True:
        try:
            inp[length]
            length += 1
        except: break
    return length

input_list = [1,2,3,4,5,6,7,8,9]
def sum_of_diagonals(input_list):
    length = find_length(input_list)
    step = length // 2
    while step * step != length:
        step -= 1
    step += 1
    # if length % 2 != 0:
    #     step = int(length / 2) - 1
    #     print(step,length)
    #     while step * step != length:
    #         step = int(step / 2) - 1
    #         print(step,step*step,length)
    #     step += 1
    # else:
    #     step = int(length / 2)
    #     while step * step != length:
    #         step = int(step/2)
    #     step += 1
    # print(step)
    sum = 0
    for i in range(0,length,step):
        sum += input_list[i]
        # print(sum,input_list[i],i)
    return (step-1,sum)

In [28]:
25/2,9/2

(12.5, 4.5)

In [35]:
import random
import numpy as np
size = [4,9,16,25]
test_cases = []
for each_size in size:
    test_cases.append([random.randrange(0,9) for i in range(each_size)])
for each_inp in test_cases:
    step,sum = sum_of_diagonals(each_inp)
    print(np.array(each_inp).reshape(step,step))
    print(sum)
    print()

[[8 5]
 [6 5]]
13

[[7 5 3]
 [2 5 0]
 [6 3 8]]
20

[[0 8 1 0]
 [0 3 5 8]
 [3 5 0 3]
 [7 8 5 5]]
8

[[1 5 2 6 5]
 [0 3 3 3 0]
 [5 8 5 2 0]
 [5 1 3 7 8]
 [4 0 2 6 2]]
18



In [33]:
size = 5
inp = np.arange(1,size * size + 1)
out = sum_of_diagonals(inp)
print(inp.reshape(out[0],out[0]))
print(out)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 65)


In [34]:
1+7+13+19+25

65